### ISSUE TITLE
wishlist 2 ?

### ISSUE THREAD

**Issue by MathieuMQc** [nushell/nana#30]
Hey guys ! I just found out about your project and I think it is awesome ! I had posted on several discord servers an idea very similar to nana about 6 month ago so I wanted to share it with you. Maybe it can inspire you ! I know you do it more for macos and windows but personnaly I think it would be awesome to do it for linux. We could be the first to have an awesome 2022 new terminal, easier than before and more accessible to the noobs. Heres the post I did 6 month ago :+1: 

Hey guys I had an crazy idea, I'm not a developper and I know it would be very hard to do but I say it anyway here :

A terminal emulator who is showing gui things. Not for the old bastard like us that loves the black terminal but for young people that discover linux. 
When you enter commands, it will have a scrolling menu (like in excel) that recommands commands, and custom simple commands with html/css output (like ls would be able to show a dolphin like screen)
and if you write it in rust everybody will LOVE you ahahah
I would love to help creating it, I'm not a developper but I can design maybe or idk
Heres a concept image :

![](https://cdn.discordapp.com/attachments/615329862395101194/985873436062662777/Untitled-1.png)

![](https://cdn.discordapp.com/attachments/615329862395101194/985873448322609182/Untitled-2.png)

**Comment by tanishqkancharla** [comment]
I don’t believe your concept image is visible

**Comment by fdncred** [comment]
I still see the images.

**Comment by rgwood** [comment]
Thanks for reaching out!
