### ISSUE TITLE
Sorting is slow, sometimes

### ISSUE THREAD

**Issue by rgwood** [nushell/nana#58]
Sorting is unexpectedly slow sometimes and I'm not sure why.

## Steps to reproduce

1. `ls` in a folder with a small number of files (~10)
2. Click on a column header a few times to sort it, reverse sort direction, repeat

Sometimes it sorts instantly, sometimes it takes almost 1s. This is on a fast Windows desktop, in release mode.

It's worth profiling or adding some instrumention to figure out where the slowdown is (Rust? React? The serialization/deserialization that occurs when passing data from the back-end to the front-end?) - it really shouldn't be this slow.

**Comment by rgwood** [comment]
Looking at the `sort_card()` Rust function, it's only taking ~300 microseconds to sort and serialize. Something else must be slow.

**Comment by fdncred** [comment]
I noticed this on Windows a week or so ago, right after sorting was implemented. I couldn't figure out a rhyme or reason why it was happening and it was unpredictable in my testing.

**Comment by rgwood** [comment]
This is looking like a Tauri bug on Windows. Still waiting on a fix.

https://github.com/tauri-apps/wry/issues/616

**Comment by tanishqkancharla** [comment]
Does this help? https://github.com/tauri-apps/wry/issues/616#issuecomment-1177725102

**Comment by rgwood** [comment]
@tanishqkancharla that's referring to an open PR: https://github.com/tauri-apps/tao/pull/465

I'm too lazy to figure out how to test that with Nana, would rather wait until a fix is released.
